name: Azure Function CI/CD

on:
  push:
    branches: 
      - 
  pull_request:
    branches:
      - 
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 
  RESOURCE_GROUP: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Runtime
        if: false
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 

      - name: Setup Node
        if: false
        uses: actions/setup-node@v3
        with:
          node-version: 

      - name: Setup Python
        if: false
        uses: actions/setup-python@v4
        with:
          python-version: 

      - name: Build
        run: echo "Add build commands based on runtime"

      - name: Package
        run: zip -r deploy.zip .

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
    if: github.event_name == 'push'
    
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Login
        uses: azure/login@v1
        with:
          creds: 

      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: 
          package: deploy.zip