name: Azure Function App Deploy

# Trigger on main branch events and manual dispatch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Environment variables from template
env:
  AZURE_FUNCTIONAPP_NAME: platformnexTestingApp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  RESOURCE_GROUP: azure_function_testing_rrs

# Define the job
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup runtime environment based on template selection
      - name: Setup node Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Azure login using service principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: 
          tenant-id: 
          subscription-id: 
          client-secret: 
      
      # Build based on runtime selection
      - name: Build Function App
        shell: bash
        run: |
          if [ "node" = "node" ]; then
            npm install
            npm run build --if-present
          elif [ "node" = "python" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          elif [ "node" = "dotnet" ] || [ "node" = "dotnet-isolated" ]; then
            dotnet build --configuration Release
          elif [ "node" = "java" ]; then
            mvn clean package
          fi
      
      # Deploy the function
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 
          package: 
          publish-profile: 
          respect-funcignore: true

      # Configure application settings
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          azcliversion: '2.50.0'
          inlineScript: |
            az functionapp config appsettings set \
              --name  \
              --resource-group  \
              --settings '@'

      # Optional: Enable monitoring if specified in template
      - name: Enable Application Insights
        if: false
        uses: azure/CLI@v1
        with:
          azcliversion: '2.50.0'
          inlineScript: |
            az monitor app-insights component create \
              --app  \
              --location canadacentral \
              --resource-group 